version: "3.3"

services:

  cryptotrader:
    container_name: cryptotrader
    image: cryptotrader:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - Binance__ApiKey=
      - Binance__Secret=
      - ConnectionStrings__Postgres=
    networks:
      - mike
networks:
  mike:
    external: true
      