using System;

    public class PriceModel1
    {      
        public float Previous1Open { get; set; }
        public float Previous1High { get; set; }
        public float Previous1Low { get; set; }
        public float Previous1Close { get; set; }
        public float Previous1Volume { get; set; }
        public float Previous1QuoteVolume { get; set; }
        public float Previous1BuyVolume { get; set; }
        public float Previous1BuyQuoteVolume { get; set; }
        public float Previous1MarketCap { get; set; }
        public float Previous1AvgOHLC { get; set; }
        public float Previous1AvgHLC { get; set; }
        public float Previous1AvgHL { get; set; }
        public float Previous1AvgOC { get; set; }
        public float Previous1ProportionUpper { get; set; }
        public float Previous1ProportionBody { get; set; }
        public float Previous1ProportionLower { get; set; }
        public float Previous1LengthCandle { get; set; }
        public float Previous1LengthUpper { get; set; }
        public float Previous1LengthBody { get; set; }
        public float Previous1LengthLower { get; set; }
        public bool Previous1CandleSticksAbandonedBabyBearish { get; set; }
        public bool Previous1CandleSticksAbandonedBabyBullish { get; set; }
        public bool Previous1CandleSticksAboveTheStomach { get; set; }
        public bool Previous1CandleSticksAdvanceBlock { get; set; }
        public bool Previous1CandleSticksBelowTheStomach { get; set; }
        public bool Previous1CandleSticksBeltHoldBearish { get; set; }
        public bool Previous1CandleSticksBeltHoldBullish { get; set; }
        public bool Previous1CandleSticksBreakawayBearish { get; set; }
        public bool Previous1CandleSticksBreakawayBullish { get; set; }
        public bool Previous1CandleSticksCandleBlack { get; set; }
        public bool Previous1CandleSticksCandleShortBlack { get; set; }
        public bool Previous1CandleSticksCandleShortWhite { get; set; }
        public bool Previous1CandleSticksCandleWhite { get; set; }
        public bool Previous1CandleSticksConcealingBabySwallow { get; set; }
        public bool Previous1CandleSticksCounterAttackBearish { get; set; }
        public bool Previous1CandleSticksCounterAttackBullish { get; set; }
        public bool Previous1CandleSticksDarkCloudCover { get; set; }
        public bool Previous1CandleSticksDeliberation { get; set; }
        public bool Previous1CandleSticksDoji { get; set; }
        public bool Previous1CandleSticksDojiDragonfly { get; set; }
        public bool Previous1CandleSticksDojiGappingDown { get; set; }
        public bool Previous1CandleSticksDojiGappingUp { get; set; }
        public bool Previous1CandleSticksDojiGravestone { get; set; }
        public bool Previous1CandleSticksDojiLongLegged { get; set; }
        public bool Previous1CandleSticksDojiNorthern { get; set; }
        public bool Previous1CandleSticksDojiSouthern { get; set; }
        public bool Previous1CandleSticksDojiStarBearish { get; set; }
        public bool Previous1CandleSticksDojiStarBullish { get; set; }
        public bool Previous1CandleSticksDojiStarCollapsing { get; set; }
        public bool Previous1CandleSticksDownsideGapThreeMethods { get; set; }
        public bool Previous1CandleSticksDownsideTasukiGap { get; set; }
        public bool Previous1CandleSticksEngulfingBearish { get; set; }
        public bool Previous1CandleSticksEngulfingBullish { get; set; }
        public bool Previous1CandleSticksEveningDojiStar { get; set; }
        public bool Previous1CandleSticksEveningStar { get; set; }
        public bool Previous1CandleSticksFallingThreeMethods { get; set; }
        public bool Previous1CandleSticksHammer { get; set; }
        public bool Previous1CandleSticksHammerInverted { get; set; }
        public bool Previous1CandleSticksHangingMan { get; set; }
        public bool Previous1CandleSticksHaramiBearish { get; set; }
        public bool Previous1CandleSticksHaramiBullish { get; set; }
        public bool Previous1CandleSticksHaramiCrossBearish { get; set; }
        public bool Previous1CandleSticksHaramiCrossBullish { get; set; }
        public bool Previous1CandleSticksHighWaveBearish { get; set; }
        public bool Previous1CandleSticksHighWaveBullish { get; set; }
        public bool Previous1CandleSticksHikkakeBearish { get; set; }
        public bool Previous1CandleSticksHikkakeBullish { get; set; }
        public bool Previous1CandleSticksHikkakeModBearish { get; set; }
        public bool Previous1CandleSticksHikkakeModBullish { get; set; }
        public bool Previous1CandleSticksHomingPidgeon { get; set; }
        public bool Previous1CandleSticksIdenticalThreeCrows { get; set; }
        public bool Previous1CandleSticksInNeck { get; set; }
        public bool Previous1CandleSticksKickingBearish { get; set; }
        public bool Previous1CandleSticksKickingBullish { get; set; }
        public bool Previous1CandleSticksKickingByLengthBearish { get; set; }
        public bool Previous1CandleSticksKickingByLengthBullish { get; set; }
        public bool Previous1CandleSticksLadderBottom { get; set; }
        public bool Previous1CandleSticksLastEngulfingBottom { get; set; }
        public bool Previous1CandleSticksLastEngulfingTop { get; set; }
        public bool Previous1CandleSticksLongBlackDay { get; set; }
        public bool Previous1CandleSticksLongWhiteDay { get; set; }
        public bool Previous1CandleSticksMarubozuBlack { get; set; }
        public bool Previous1CandleSticksMarubozuClosingBlack { get; set; }
        public bool Previous1CandleSticksMarubozuClosingWhite { get; set; }
        public bool Previous1CandleSticksMarubozuOpeningBlack { get; set; }
        public bool Previous1CandleSticksMarubozuOpeningWhite { get; set; }
        public bool Previous1CandleSticksMarubozuWhite { get; set; }
        public bool Previous1CandleSticksMatchingLow { get; set; }
        public bool Previous1CandleSticksMatHold { get; set; }
        public bool Previous1CandleSticksMeetingLinesBearish { get; set; }
        public bool Previous1CandleSticksMeetingLinesBullish { get; set; }
        public bool Previous1CandleSticksMorningDojiStar { get; set; }
        public bool Previous1CandleSticksMorningStar { get; set; }
        public bool Previous1CandleSticksOnNeck { get; set; }
        public bool Previous1CandleSticksPiercingPattern { get; set; }
        public bool Previous1CandleSticksRickshawMan { get; set; }
        public bool Previous1CandleSticksRisingThreeMethods { get; set; }
        public bool Previous1CandleSticksSeparatingLinesBearish { get; set; }
        public bool Previous1CandleSticksSeparatingLinesBullish { get; set; }
        public bool Previous1CandleSticksShootingStarOneCandle { get; set; }
        public bool Previous1CandleSticksShootingStarTwoCandle { get; set; }
        public bool Previous1CandleSticksShortLineBearish { get; set; }
        public bool Previous1CandleSticksShortLineBullish { get; set; }
        public bool Previous1CandleSticksSideBySideWhiteLinesBearish { get; set; }
        public bool Previous1CandleSticksSideBySideWhiteLinesBullish { get; set; }
        public bool Previous1CandleSticksSpinningTopBlack { get; set; }
        public bool Previous1CandleSticksSpinningTopWhite { get; set; }
        public bool Previous1CandleSticksStalledPattern { get; set; }
        public bool Previous1CandleSticksStickSandwich { get; set; }
        public bool Previous1CandleSticksTakuriLine { get; set; }
        public bool Previous1CandleSticksThreeBlackCrows { get; set; }
        public bool Previous1CandleSticksThreeInsideDown { get; set; }
        public bool Previous1CandleSticksThreeInsideUp { get; set; }
        public bool Previous1CandleSticksThreeLineStrikeBearish { get; set; }
        public bool Previous1CandleSticksThreeLineStrikeBullish { get; set; }
        public bool Previous1CandleSticksThreeOutsideDown { get; set; }
        public bool Previous1CandleSticksThreeOutsideUp { get; set; }
        public bool Previous1CandleSticksThreeStarsInTheSouth { get; set; }
        public bool Previous1CandleSticksThreeWhiteSoldiers { get; set; }
        public bool Previous1CandleSticksThrusting { get; set; }
        public bool Previous1CandleSticksTriStarBearish { get; set; }
        public bool Previous1CandleSticksTriStarBullish { get; set; }
        public bool Previous1CandleSticksTweezersBottom { get; set; }
        public bool Previous1CandleSticksTweezersTop { get; set; }
        public bool Previous1CandleSticksTwoBlackGappingCandles { get; set; }
        public bool Previous1CandleSticksTwoCrows { get; set; }
        public bool Previous1CandleSticksUniqueThreeRiverBottom { get; set; }
        public bool Previous1CandleSticksUpsideGapSideBySideWhiteLineBearish { get; set; }
        public bool Previous1CandleSticksUpsideGapSideBySideWhiteLineBullish { get; set; }
        public bool Previous1CandleSticksUpsideGapThreeMethods { get; set; }
        public bool Previous1CandleSticksUpsideGapTwoCrows { get; set; }
        public bool Previous1CandleSticksUpsideTasukiGap { get; set; }
        public bool Previous1CandleSticksWindowFalling { get; set; }
        public bool Previous1CandleSticksWindowRising { get; set; }
        public float Previous1CyclesEhlersAdaptiveCyberCycleCycle { get; set; }
        public float Previous1CyclesEhlersAdaptiveCyberCyclePeriod { get; set; }
        public float Previous1CyclesEhlersCombFilterSpectralEstimate { get; set; }
        public float Previous1CyclesEhlersCyberCycle { get; set; }
        public float Previous1CyclesEhlersCycleAmplitude { get; set; }
        public float Previous1CyclesEhlersCycleBandPassFilter { get; set; }
        public float Previous1CyclesEhlersDualDifferentiatorDominantCycle { get; set; }
        public float Previous1CyclesEhlersEvenBetterSineWaveIndicator { get; set; }
        public float Previous1CyclesEhlersFourierSeriesAnalysisWave { get; set; }
        public float Previous1CyclesEhlersFourierSeriesAnalysisRoc { get; set; }
        public float Previous1CyclesEhlersHomodyneDominantCycle { get; set; }
        public float Previous1CyclesEhlersInstantaneousPhaseIndicator { get; set; }
        public float Previous1CyclesEhlersPhaseAccumulationDominantCycle { get; set; }
        public float Previous1CyclesEhlersSimpleCycleIndicator { get; set; }
        public float Previous1CyclesEhlersSineWaveIndicatorV1Sine { get; set; }
        public float Previous1CyclesEhlersSineWaveIndicatorV1LeadSine { get; set; }
        public float Previous1CyclesEhlersSineWaveIndicatorV2Sine { get; set; }
        public float Previous1CyclesEhlersSineWaveIndicatorV2LeadSine { get; set; }
        public float Previous1CyclesEhlersSpectrumDerivedFilterBank { get; set; }
        public float Previous1CyclesEhlersSquelchIndicator { get; set; }
        public float Previous1CyclesEhlersStochasticCyberCycleCycle { get; set; }
        public float Previous1CyclesEhlersStochasticCyberCycleSignal { get; set; }
        public float Previous1CyclesEhlersZeroCrossingsDominantCycle { get; set; }
        public float Previous1CyclesGroverLlorensCycleOscillator { get; set; }
        public float Previous1CyclesHurstCycleChannelFastUpperBand { get; set; }
        public float Previous1CyclesHurstCycleChannelSlowUpperBand { get; set; }
        public float Previous1CyclesHurstCycleChannelFastMiddleBand { get; set; }
        public float Previous1CyclesHurstCycleChannelSlowMiddleBand { get; set; }
        public float Previous1CyclesHurstCycleChannelFastLowerBand { get; set; }
        public float Previous1CyclesHurstCycleChannelSlowLowerBand { get; set; }
        public float Previous1CyclesHurstCycleChannelOMed { get; set; }
        public float Previous1CyclesHurstCycleChannelOShort { get; set; }
        public float Previous1CyclesSimpleCycle { get; set; }
        public float Previous1MAALMA6 { get; set; }
        public float Previous1MAALMA12 { get; set; }
        public float Previous1MAALMA24 { get; set; }
        public float Previous1MAALMA168 { get; set; }
        public float Previous1MADEMA6 { get; set; }
        public float Previous1MADEMA12 { get; set; }
        public float Previous1MADEMA24 { get; set; }
        public float Previous1MADEMA168 { get; set; }
        public float Previous1MAEMA6 { get; set; }
        public float Previous1MAEMA12 { get; set; }
        public float Previous1MAEMA24 { get; set; }
        public float Previous1MAEMA168 { get; set; }
        public float Previous1MAEPMA6 { get; set; }
        public float Previous1MAEPMA12 { get; set; }
        public float Previous1MAEPMA24 { get; set; }
        public float Previous1MAEPMA168 { get; set; }
        public float Previous1MAHMA6 { get; set; }
        public float Previous1MAHMA12 { get; set; }
        public float Previous1MAHMA24 { get; set; }
        public float Previous1MAHMA168 { get; set; }
        public float Previous1MAKAMAER { get; set; }
        public float Previous1MAKAMAKama { get; set; }
        public float Previous1MAMAMAMAMA { get; set; }
        public float Previous1MAMAMAFAMA { get; set; }
        public float Previous1MASMA12Sma { get; set; }
        public float Previous1MASMA12Mad { get; set; }
        public float Previous1MASMA12Mse { get; set; }
        public float Previous1MASMA12Mape { get; set; }
        public float Previous1MASMA24Sma { get; set; }
        public float Previous1MASMA24Mad { get; set; }
        public float Previous1MASMA24Mse { get; set; }
        public float Previous1MASMA24Mape { get; set; }
        public float Previous1MASMA168Sma { get; set; }
        public float Previous1MASMA168Mad { get; set; }
        public float Previous1MASMA168Mse { get; set; }
        public float Previous1MASMA168Mape { get; set; }
        public float Previous1MASMMA6 { get; set; }
        public float Previous1MASMMA12 { get; set; }
        public float Previous1MASMMA24 { get; set; }
        public float Previous1MASMMA168 { get; set; }
        public float Previous1MAT3_6 { get; set; }
        public float Previous1MAT3_12 { get; set; }
        public float Previous1MAT3_24 { get; set; }
        public float Previous1MAT3_168 { get; set; }
        public float Previous1MATEMA6 { get; set; }
        public float Previous1MATEMA12 { get; set; }
        public float Previous1MATEMA24 { get; set; }
        public float Previous1MATEMA168 { get; set; }
        public float Previous1MAWMA6 { get; set; }
        public float Previous1MAWMA12 { get; set; }
        public float Previous1MAWMA24 { get; set; }
        public float Previous1MAWMA168 { get; set; }
        public float Previous1MAVWMA6 { get; set; }
        public float Previous1MAVWMA12 { get; set; }
        public float Previous1MAVWMA24 { get; set; }
        public float Previous1MAVWMA168 { get; set; }
        public float Previous1MomentumAbsolutePriceOscillator { get; set; }
        public float Previous1MomentumAwesomeOscillatorOscillator { get; set; }
        public float Previous1MomentumAwesomeOscillatorNormalized { get; set; }
        public float Previous1MomentumBalanceOfPower { get; set; }
        public float Previous1MomentumChandeMomentumOscillator { get; set; }
        public float Previous1MomentumCommodityChannelIndex { get; set; }
        public float Previous1MomentumCommoditySelectionIndexCsi { get; set; }
        public float Previous1MomentumCommoditySelectionIndexSignal { get; set; }
        public float Previous1MomentumConnorsRSIRsi { get; set; }
        public float Previous1MomentumConnorsRSIRsiStreak { get; set; }
        public float Previous1MomentumConnorsRSIPercentRank { get; set; }
        public float Previous1MomentumConnorsRSIConnorsRsi { get; set; }
        public float Previous1MomentumDetrendedPriceOscillatorSma { get; set; }
        public float Previous1MomentumDetrendedPriceOscillatorDpo { get; set; }
        public float Previous1MomentumElderRayIndexBull { get; set; }
        public float Previous1MomentumElderRayIndexBear { get; set; }
        public float Previous1MomentumGatorOscillatorUpper { get; set; }
        public float Previous1MomentumGatorOscillatorLower { get; set; }
        public bool Previous1MomentumGatorOscillatorUpperExpanding { get; set; }
        public bool Previous1MomentumGatorOscillatorLowerExpanding { get; set; }
        public float Previous1MomentumMACDMacd { get; set; }
        public float Previous1MomentumMACDSignal { get; set; }
        public float Previous1MomentumMACDHistogram { get; set; }
        public float Previous1MomentumOnBalanceVolumeObv { get; set; }
        public float Previous1MomentumOnBalanceVolumeSma { get; set; }
        public float Previous1MomentumPercentagePriceOscillatorPpo { get; set; }
        public float Previous1MomentumPercentagePriceOscillatorSignal { get; set; }
        public float Previous1MomentumPercentagePriceOscillatorHistogram { get; set; }
        public float Previous1MomentumPriceMomentumOscillatorPmo { get; set; }
        public float Previous1MomentumPriceMomentumOscillatorSignal { get; set; }
        public float Previous1MomentumRateOfChangeMomentum { get; set; }
        public float Previous1MomentumRateOfChangeRoc { get; set; }
        public float Previous1MomentumRateOfChangeSma { get; set; }
        public float Previous1MomentumRelativeStrengthIndex { get; set; }
        public float Previous1MomentumRocWithBandsRoc { get; set; }
        public float Previous1MomentumRocWithBandsEma { get; set; }
        public float Previous1MomentumRocWithBandsUpper { get; set; }
        public float Previous1MomentumRocWithBandsLower { get; set; }
        public float Previous1MomentumSchaffTrendCycle { get; set; }
        public float Previous1MomentumStochasticFastOscillatorSfo { get; set; }
        public float Previous1MomentumStochasticFastOscillatorSignal { get; set; }
        public float Previous1MomentumStochasticMomentumIndexSmi { get; set; }
        public float Previous1MomentumStochasticMomentumIndexSignal { get; set; }
        public float Previous1MomentumStochasticOscillatorOscillator { get; set; }
        public float Previous1MomentumStochasticOscillatorSignal { get; set; }
        public float Previous1MomentumStochasticOscillatorPercentJ { get; set; }
        public float Previous1MomentumStochasticRSIStochRsi { get; set; }
        public float Previous1MomentumStochasticRSISignal { get; set; }
        public float Previous1MomentumTRIXEMA3 { get; set; }
        public float Previous1MomentumTRIXTrix { get; set; }
        public float Previous1MomentumTRIXSignal { get; set; }
        public float Previous1MomentumTrueStrengthIndexTsi { get; set; }
        public float Previous1MomentumTrueStrengthIndexSignal { get; set; }
        public float Previous1MomentumUltimateOscillator { get; set; }
        public float Previous1MomentumWilliamsR { get; set; }
        public float Previous1OtherIndicatorsFractalChaosBandsUpper { get; set; }
        public float Previous1OtherIndicatorsFractalChaosBandsLower { get; set; }
        public float Previous1OtherIndicatorsHurstExponent { get; set; }
        public float Previous1OtherIndicatorsPivotHighPoint { get; set; }
        public float Previous1OtherIndicatorsPivotLowPoint { get; set; }
        public float Previous1OtherIndicatorsPivotHighLine { get; set; }
        public float Previous1OtherIndicatorsPivotLowLine { get; set; }
        public bool Previous1OtherIndicatorsPivotHighTrendNone { get; set; }
        public bool Previous1OtherIndicatorsPivotHighTrendHigherHigh { get; set; }
        public bool Previous1OtherIndicatorsPivotHighTrendLowerHigh { get; set; }
        public bool Previous1OtherIndicatorsPivotHighTrendHigherLow { get; set; }
        public bool Previous1OtherIndicatorsPivotHighTrendLowerLow { get; set; }
        public bool Previous1OtherIndicatorsPivotLowTrendNone { get; set; }
        public bool Previous1OtherIndicatorsPivotLowTrendHigherHigh { get; set; }
        public bool Previous1OtherIndicatorsPivotLowTrendLowerHigh { get; set; }
        public bool Previous1OtherIndicatorsPivotLowTrendHigherLow { get; set; }
        public bool Previous1OtherIndicatorsPivotLowTrendLowerLow { get; set; }
        public float Previous1OtherIndicatorsPivotPointsR1 { get; set; }
        public float Previous1OtherIndicatorsPivotPointsR2 { get; set; }
        public float Previous1OtherIndicatorsPivotPointsR3 { get; set; }
        public float Previous1OtherIndicatorsPivotPointsPP { get; set; }
        public float Previous1OtherIndicatorsPivotPointsS1 { get; set; }
        public float Previous1OtherIndicatorsPivotPointsS2 { get; set; }
        public float Previous1OtherIndicatorsPivotPointsS3 { get; set; }
        public float Previous1OtherIndicatorsPriceRelativeStrengthPrs { get; set; }
        public float Previous1OtherIndicatorsPriceRelativeStrengthSma { get; set; }
        public float Previous1OtherIndicatorsPriceRelativeStrengthPercent { get; set; }
        public float Previous1OtherIndicatorsProjectionOscillatorPbo { get; set; }
        public float Previous1OtherIndicatorsProjectionOscillatorSignal { get; set; }
        public float Previous1OtherIndicatorsRollingPivotPointsR1 { get; set; }
        public float Previous1OtherIndicatorsRollingPivotPointsR2 { get; set; }
        public float Previous1OtherIndicatorsRollingPivotPointsR3 { get; set; }
        public float Previous1OtherIndicatorsRollingPivotPointsPP { get; set; }
        public float Previous1OtherIndicatorsRollingPivotPointsS1 { get; set; }
        public float Previous1OtherIndicatorsRollingPivotPointsS2 { get; set; }
        public float Previous1OtherIndicatorsRollingPivotPointsS3 { get; set; }
        public float Previous1OtherIndicatorsWilliamsFractalFractalBear { get; set; }
        public float Previous1OtherIndicatorsWilliamsFractalFractalBull { get; set; }
        public float Previous1OtherIndicatorsVerticalHorizontalFilterVhf { get; set; }
        public float Previous1OtherIndicatorsVerticalHorizontalFilterSignal { get; set; }
        public bool Previous1PeakHighestHigh { get; set; }
        public float Previous1PeakOffsetPreviousHH { get; set; }
        public float Previous1PeakOffsetNextHH { get; set; }
        public bool Previous1PeakLowestLow { get; set; }
        public float Previous1PeakOffsetPreviousLL { get; set; }
        public float Previous1PeakOffsetNextLL { get; set; }
        public float Previous1ReturnDayReturn { get; set; }
        public float Previous1ReturnDayInterval { get; set; }
        public float Previous1ReturnDayRank2 { get; set; }
        public float Previous1ReturnDayRank3 { get; set; }
        public float Previous1ReturnDayRank4 { get; set; }
        public float Previous1ReturnDayRank6 { get; set; }
        public float Previous1ReturnDayRank8 { get; set; }
        public float Previous1ReturnDayRank12 { get; set; }
        public float Previous1ReturnTwoDayReturn { get; set; }
        public float Previous1ReturnTwoDayInterval { get; set; }
        public float Previous1ReturnTwoDayRank2 { get; set; }
        public float Previous1ReturnTwoDayRank3 { get; set; }
        public float Previous1ReturnTwoDayRank4 { get; set; }
        public float Previous1ReturnTwoDayRank6 { get; set; }
        public float Previous1ReturnTwoDayRank8 { get; set; }
        public float Previous1ReturnTwoDayRank12 { get; set; }
        public float Previous1ReturnWeekReturn { get; set; }
        public float Previous1ReturnWeekInterval { get; set; }
        public float Previous1ReturnWeekRank2 { get; set; }
        public float Previous1ReturnWeekRank3 { get; set; }
        public float Previous1ReturnWeekRank4 { get; set; }
        public float Previous1ReturnWeekRank6 { get; set; }
        public float Previous1ReturnWeekRank8 { get; set; }
        public float Previous1ReturnWeekRank12 { get; set; }
        public float Previous1TrendSlopeHigh6 { get; set; }
        public float Previous1TrendSlopeHigh8 { get; set; }
        public float Previous1TrendSlopeHigh12 { get; set; }
        public float Previous1TrendSlopeHigh24 { get; set; }
        public float Previous1TrendSlopeLow6 { get; set; }
        public float Previous1TrendSlopeLow8 { get; set; }
        public float Previous1TrendSlopeLow12 { get; set; }
        public float Previous1TrendSlopeLow24 { get; set; }
        public float Previous1TrendAroonUp { get; set; }
        public float Previous1TrendAroonDown { get; set; }
        public float Previous1TrendAroonOscillator { get; set; }
        public float Previous1TrendADXPdi { get; set; }
        public float Previous1TrendADXMdi { get; set; }
        public float Previous1TrendADXAdx { get; set; }
        public float Previous1TrendADXAdxr { get; set; }
        public float Previous1TrendAtrTrailingStopAtrStop { get; set; }
        public float Previous1TrendAtrTrailingStopBuyStop { get; set; }
        public float Previous1TrendAtrTrailingStopSellStop { get; set; }
        public float Previous1TrendChandelierExitShort { get; set; }
        public float Previous1TrendChandelierExitLong { get; set; }
        public float Previous1TrendHilbertTransformDominantCyclePeriods { get; set; }
        public float Previous1TrendHilbertTransformTrendLine { get; set; }
        public float Previous1TrendHilbertTransformSmoothPrice { get; set; }
        public float Previous1TrendIchimokuCloudSignal { get; set; }
        public float Previous1TrendIchimokuCloudBase { get; set; }
        public float Previous1TrendIchimokuCloudLeadingA { get; set; }
        public float Previous1TrendIchimokuCloudLeadingB { get; set; }
        public float Previous1TrendIchimokuCloudLagging { get; set; }
        public float Previous1TrendMcGinleyDynamicMcGinleyDynamic6 { get; set; }
        public float Previous1TrendMcGinleyDynamicMcGinleyDynamic12 { get; set; }
        public float Previous1TrendMcGinleyDynamicMcGinleyDynamic24 { get; set; }
        public float Previous1TrendMcGinleyDynamicMcGinleyDynamic168 { get; set; }
        public float Previous1TrendMovingAverageEnvelopeUpper { get; set; }
        public float Previous1TrendMovingAverageEnvelopeCenter { get; set; }
        public float Previous1TrendMovingAverageEnvelopeLower { get; set; }
        public float Previous1TrendParabolicSARSAR { get; set; }
        public bool Previous1TrendParabolicSARIsReversal { get; set; }
        public float Previous1TrendSuperTrendCombined { get; set; }
        public float Previous1TrendSuperTrendUpper { get; set; }
        public float Previous1TrendSuperTrendLower { get; set; }
        public float Previous1TrendVortexIndicatorPvi { get; set; }
        public float Previous1TrendVortexIndicatorNvi { get; set; }
        public float Previous1TrendWilliamsAlligatorJaw { get; set; }
        public float Previous1TrendWilliamsAlligatorTeeth { get; set; }
        public float Previous1TrendWilliamsAlligatorLips { get; set; }
        public float Previous1VolatilityATR12TR { get; set; }
        public float Previous1VolatilityATR12Atr { get; set; }
        public float Previous1VolatilityATR12Atrp { get; set; }
        public float Previous1VolatilityATR24TR { get; set; }
        public float Previous1VolatilityATR24Atr { get; set; }
        public float Previous1VolatilityATR24Atrp { get; set; }
        public float Previous1VolatilityATR168TR { get; set; }
        public float Previous1VolatilityATR168Atr { get; set; }
        public float Previous1VolatilityATR168Atrp { get; set; }
        public float Previous1VolatilityBollingerBandsUpper { get; set; }
        public float Previous1VolatilityBollingerBandsLower { get; set; }
        public float Previous1VolatilityBollingerBandsPercentB { get; set; }
        public float Previous1VolatilityBollingerBandsZScore { get; set; }
        public float Previous1VolatilityBollingerBandsWidth { get; set; }
        public float Previous1VolatilityChoppinessIndex { get; set; }
        public float Previous1VolatilityDonchianChannelsUpper { get; set; }
        public float Previous1VolatilityDonchianChannelsCenter { get; set; }
        public float Previous1VolatilityDonchianChannelsLower { get; set; }
        public float Previous1VolatilityDonchianChannelsWidth { get; set; }
        public float Previous1VolatilityHistoricalVolatility { get; set; }
        public float Previous1VolatilityKeltnerChannelsUpper { get; set; }
        public float Previous1VolatilityKeltnerChannelsCenter { get; set; }
        public float Previous1VolatilityKeltnerChannelsLower { get; set; }
        public float Previous1VolatilityKeltnerChannelsWidth { get; set; }
        public float Previous1VolatilityStandardDeviationChannelUpper { get; set; }
        public float Previous1VolatilityStandardDeviationChannelCenter { get; set; }
        public float Previous1VolatilityStandardDeviationChannelLower { get; set; }
        public bool Previous1VolatilityStandardDeviationChannelBreakPoint { get; set; }
        public float Previous1VolatilityStarcBandUpper { get; set; }
        public float Previous1VolatilityStarcBandCenter { get; set; }
        public float Previous1VolatilityStarcBandLower { get; set; }
        public float Previous1VolatilityUlcerIndex { get; set; }
        public float Previous1VolatilityVolatilityStopSAR { get; set; }
        public bool Previous1VolatilityVolatilityStopIsStop { get; set; }
        public float Previous1VolatilityVolatilityStopUpper { get; set; }
        public float Previous1VolatilityVolatilityStopLower { get; set; }
        public float Previous1VolumesAccumulationDistributionLineMoneyFlowMultiplier { get; set; }
        public float Previous1VolumesAccumulationDistributionLineMoneyFlowVolume { get; set; }
        public float Previous1VolumesAccumulationDistributionLineAdl { get; set; }
        public float Previous1VolumesAccumulationDistributionLineAdlSma { get; set; }
        public float Previous1VolumesChaikinMoneyFlowMoneyFlowMultiplier { get; set; }
        public float Previous1VolumesChaikinMoneyFlowMoneyFlowVolume { get; set; }
        public float Previous1VolumesChaikinMoneyFlowCmf { get; set; }
        public float Previous1VolumesChaikinOscillatorMoneyFlowMultiplier { get; set; }
        public float Previous1VolumesChaikinOscillatorMoneyFlowVolume { get; set; }
        public float Previous1VolumesChaikinOscillatorAdl { get; set; }
        public float Previous1VolumesChaikinOscillatorOscillator { get; set; }
        public float Previous1VolumesForceIndex { get; set; }
        public float Previous1VolumesKlingerVolumeOscillatorOscillator { get; set; }
        public float Previous1VolumesKlingerVolumeOscillatorSignal { get; set; }
        public float Previous1VolumesMoneyFlowIndex { get; set; }
        public float Previous1VolumesPercentageVolumeOscillatorPvo { get; set; }
        public float Previous1VolumesPercentageVolumeOscillatorSignal { get; set; }
        public float Previous1VolumesPercentageVolumeOscillatorHistogram { get; set; }

        public float CurrentOpen { get; set; }
        public float CurrentHigh { get; set; }
        public float CurrentLow { get; set; }
        public float CurrentClose { get; set; }
        public float CurrentVolume { get; set; }
        public float CurrentQuoteVolume { get; set; }
        public float CurrentBuyVolume { get; set; }
        public float CurrentBuyQuoteVolume { get; set; }
        public float CurrentMarketCap { get; set; }
        public float CurrentAvgOHLC { get; set; }
        public float CurrentAvgHLC { get; set; }
        public float CurrentAvgHL { get; set; }
        public float CurrentAvgOC { get; set; }
        public float CurrentProportionUpper { get; set; }
        public float CurrentProportionBody { get; set; }
        public float CurrentProportionLower { get; set; }
        public float CurrentLengthCandle { get; set; }
        public float CurrentLengthUpper { get; set; }
        public float CurrentLengthBody { get; set; }
        public float CurrentLengthLower { get; set; }
        public bool CurrentCandleSticksAbandonedBabyBearish { get; set; }
        public bool CurrentCandleSticksAbandonedBabyBullish { get; set; }
        public bool CurrentCandleSticksAboveTheStomach { get; set; }
        public bool CurrentCandleSticksAdvanceBlock { get; set; }
        public bool CurrentCandleSticksBelowTheStomach { get; set; }
        public bool CurrentCandleSticksBeltHoldBearish { get; set; }
        public bool CurrentCandleSticksBeltHoldBullish { get; set; }
        public bool CurrentCandleSticksBreakawayBearish { get; set; }
        public bool CurrentCandleSticksBreakawayBullish { get; set; }
        public bool CurrentCandleSticksCandleBlack { get; set; }
        public bool CurrentCandleSticksCandleShortBlack { get; set; }
        public bool CurrentCandleSticksCandleShortWhite { get; set; }
        public bool CurrentCandleSticksCandleWhite { get; set; }
        public bool CurrentCandleSticksConcealingBabySwallow { get; set; }
        public bool CurrentCandleSticksCounterAttackBearish { get; set; }
        public bool CurrentCandleSticksCounterAttackBullish { get; set; }
        public bool CurrentCandleSticksDarkCloudCover { get; set; }
        public bool CurrentCandleSticksDeliberation { get; set; }
        public bool CurrentCandleSticksDoji { get; set; }
        public bool CurrentCandleSticksDojiDragonfly { get; set; }
        public bool CurrentCandleSticksDojiGappingDown { get; set; }
        public bool CurrentCandleSticksDojiGappingUp { get; set; }
        public bool CurrentCandleSticksDojiGravestone { get; set; }
        public bool CurrentCandleSticksDojiLongLegged { get; set; }
        public bool CurrentCandleSticksDojiNorthern { get; set; }
        public bool CurrentCandleSticksDojiSouthern { get; set; }
        public bool CurrentCandleSticksDojiStarBearish { get; set; }
        public bool CurrentCandleSticksDojiStarBullish { get; set; }
        public bool CurrentCandleSticksDojiStarCollapsing { get; set; }
        public bool CurrentCandleSticksDownsideGapThreeMethods { get; set; }
        public bool CurrentCandleSticksDownsideTasukiGap { get; set; }
        public bool CurrentCandleSticksEngulfingBearish { get; set; }
        public bool CurrentCandleSticksEngulfingBullish { get; set; }
        public bool CurrentCandleSticksEveningDojiStar { get; set; }
        public bool CurrentCandleSticksEveningStar { get; set; }
        public bool CurrentCandleSticksFallingThreeMethods { get; set; }
        public bool CurrentCandleSticksHammer { get; set; }
        public bool CurrentCandleSticksHammerInverted { get; set; }
        public bool CurrentCandleSticksHangingMan { get; set; }
        public bool CurrentCandleSticksHaramiBearish { get; set; }
        public bool CurrentCandleSticksHaramiBullish { get; set; }
        public bool CurrentCandleSticksHaramiCrossBearish { get; set; }
        public bool CurrentCandleSticksHaramiCrossBullish { get; set; }
        public bool CurrentCandleSticksHighWaveBearish { get; set; }
        public bool CurrentCandleSticksHighWaveBullish { get; set; }
        public bool CurrentCandleSticksHikkakeBearish { get; set; }
        public bool CurrentCandleSticksHikkakeBullish { get; set; }
        public bool CurrentCandleSticksHikkakeModBearish { get; set; }
        public bool CurrentCandleSticksHikkakeModBullish { get; set; }
        public bool CurrentCandleSticksHomingPidgeon { get; set; }
        public bool CurrentCandleSticksIdenticalThreeCrows { get; set; }
        public bool CurrentCandleSticksInNeck { get; set; }
        public bool CurrentCandleSticksKickingBearish { get; set; }
        public bool CurrentCandleSticksKickingBullish { get; set; }
        public bool CurrentCandleSticksKickingByLengthBearish { get; set; }
        public bool CurrentCandleSticksKickingByLengthBullish { get; set; }
        public bool CurrentCandleSticksLadderBottom { get; set; }
        public bool CurrentCandleSticksLastEngulfingBottom { get; set; }
        public bool CurrentCandleSticksLastEngulfingTop { get; set; }
        public bool CurrentCandleSticksLongBlackDay { get; set; }
        public bool CurrentCandleSticksLongWhiteDay { get; set; }
        public bool CurrentCandleSticksMarubozuBlack { get; set; }
        public bool CurrentCandleSticksMarubozuClosingBlack { get; set; }
        public bool CurrentCandleSticksMarubozuClosingWhite { get; set; }
        public bool CurrentCandleSticksMarubozuOpeningBlack { get; set; }
        public bool CurrentCandleSticksMarubozuOpeningWhite { get; set; }
        public bool CurrentCandleSticksMarubozuWhite { get; set; }
        public bool CurrentCandleSticksMatchingLow { get; set; }
        public bool CurrentCandleSticksMatHold { get; set; }
        public bool CurrentCandleSticksMeetingLinesBearish { get; set; }
        public bool CurrentCandleSticksMeetingLinesBullish { get; set; }
        public bool CurrentCandleSticksMorningDojiStar { get; set; }
        public bool CurrentCandleSticksMorningStar { get; set; }
        public bool CurrentCandleSticksOnNeck { get; set; }
        public bool CurrentCandleSticksPiercingPattern { get; set; }
        public bool CurrentCandleSticksRickshawMan { get; set; }
        public bool CurrentCandleSticksRisingThreeMethods { get; set; }
        public bool CurrentCandleSticksSeparatingLinesBearish { get; set; }
        public bool CurrentCandleSticksSeparatingLinesBullish { get; set; }
        public bool CurrentCandleSticksShootingStarOneCandle { get; set; }
        public bool CurrentCandleSticksShootingStarTwoCandle { get; set; }
        public bool CurrentCandleSticksShortLineBearish { get; set; }
        public bool CurrentCandleSticksShortLineBullish { get; set; }
        public bool CurrentCandleSticksSideBySideWhiteLinesBearish { get; set; }
        public bool CurrentCandleSticksSideBySideWhiteLinesBullish { get; set; }
        public bool CurrentCandleSticksSpinningTopBlack { get; set; }
        public bool CurrentCandleSticksSpinningTopWhite { get; set; }
        public bool CurrentCandleSticksStalledPattern { get; set; }
        public bool CurrentCandleSticksStickSandwich { get; set; }
        public bool CurrentCandleSticksTakuriLine { get; set; }
        public bool CurrentCandleSticksThreeBlackCrows { get; set; }
        public bool CurrentCandleSticksThreeInsideDown { get; set; }
        public bool CurrentCandleSticksThreeInsideUp { get; set; }
        public bool CurrentCandleSticksThreeLineStrikeBearish { get; set; }
        public bool CurrentCandleSticksThreeLineStrikeBullish { get; set; }
        public bool CurrentCandleSticksThreeOutsideDown { get; set; }
        public bool CurrentCandleSticksThreeOutsideUp { get; set; }
        public bool CurrentCandleSticksThreeStarsInTheSouth { get; set; }
        public bool CurrentCandleSticksThreeWhiteSoldiers { get; set; }
        public bool CurrentCandleSticksThrusting { get; set; }
        public bool CurrentCandleSticksTriStarBearish { get; set; }
        public bool CurrentCandleSticksTriStarBullish { get; set; }
        public bool CurrentCandleSticksTweezersBottom { get; set; }
        public bool CurrentCandleSticksTweezersTop { get; set; }
        public bool CurrentCandleSticksTwoBlackGappingCandles { get; set; }
        public bool CurrentCandleSticksTwoCrows { get; set; }
        public bool CurrentCandleSticksUniqueThreeRiverBottom { get; set; }
        public bool CurrentCandleSticksUpsideGapSideBySideWhiteLineBearish { get; set; }
        public bool CurrentCandleSticksUpsideGapSideBySideWhiteLineBullish { get; set; }
        public bool CurrentCandleSticksUpsideGapThreeMethods { get; set; }
        public bool CurrentCandleSticksUpsideGapTwoCrows { get; set; }
        public bool CurrentCandleSticksUpsideTasukiGap { get; set; }
        public bool CurrentCandleSticksWindowFalling { get; set; }
        public bool CurrentCandleSticksWindowRising { get; set; }
        public float CurrentCyclesEhlersAdaptiveCyberCycleCycle { get; set; }
        public float CurrentCyclesEhlersAdaptiveCyberCyclePeriod { get; set; }
        public float CurrentCyclesEhlersCombFilterSpectralEstimate { get; set; }
        public float CurrentCyclesEhlersCyberCycle { get; set; }
        public float CurrentCyclesEhlersCycleAmplitude { get; set; }
        public float CurrentCyclesEhlersCycleBandPassFilter { get; set; }
        public float CurrentCyclesEhlersDualDifferentiatorDominantCycle { get; set; }
        public float CurrentCyclesEhlersEvenBetterSineWaveIndicator { get; set; }
        public float CurrentCyclesEhlersFourierSeriesAnalysisWave { get; set; }
        public float CurrentCyclesEhlersFourierSeriesAnalysisRoc { get; set; }
        public float CurrentCyclesEhlersHomodyneDominantCycle { get; set; }
        public float CurrentCyclesEhlersInstantaneousPhaseIndicator { get; set; }
        public float CurrentCyclesEhlersPhaseAccumulationDominantCycle { get; set; }
        public float CurrentCyclesEhlersSimpleCycleIndicator { get; set; }
        public float CurrentCyclesEhlersSineWaveIndicatorV1Sine { get; set; }
        public float CurrentCyclesEhlersSineWaveIndicatorV1LeadSine { get; set; }
        public float CurrentCyclesEhlersSineWaveIndicatorV2Sine { get; set; }
        public float CurrentCyclesEhlersSineWaveIndicatorV2LeadSine { get; set; }
        public float CurrentCyclesEhlersSpectrumDerivedFilterBank { get; set; }
        public float CurrentCyclesEhlersSquelchIndicator { get; set; }
        public float CurrentCyclesEhlersStochasticCyberCycleCycle { get; set; }
        public float CurrentCyclesEhlersStochasticCyberCycleSignal { get; set; }
        public float CurrentCyclesEhlersZeroCrossingsDominantCycle { get; set; }
        public float CurrentCyclesGroverLlorensCycleOscillator { get; set; }
        public float CurrentCyclesHurstCycleChannelFastUpperBand { get; set; }
        public float CurrentCyclesHurstCycleChannelSlowUpperBand { get; set; }
        public float CurrentCyclesHurstCycleChannelFastMiddleBand { get; set; }
        public float CurrentCyclesHurstCycleChannelSlowMiddleBand { get; set; }
        public float CurrentCyclesHurstCycleChannelFastLowerBand { get; set; }
        public float CurrentCyclesHurstCycleChannelSlowLowerBand { get; set; }
        public float CurrentCyclesHurstCycleChannelOMed { get; set; }
        public float CurrentCyclesHurstCycleChannelOShort { get; set; }
        public float CurrentCyclesSimpleCycle { get; set; }
        public float CurrentMAALMA6 { get; set; }
        public float CurrentMAALMA12 { get; set; }
        public float CurrentMAALMA24 { get; set; }
        public float CurrentMAALMA168 { get; set; }
        public float CurrentMADEMA6 { get; set; }
        public float CurrentMADEMA12 { get; set; }
        public float CurrentMADEMA24 { get; set; }
        public float CurrentMADEMA168 { get; set; }
        public float CurrentMAEMA6 { get; set; }
        public float CurrentMAEMA12 { get; set; }
        public float CurrentMAEMA24 { get; set; }
        public float CurrentMAEMA168 { get; set; }
        public float CurrentMAEPMA6 { get; set; }
        public float CurrentMAEPMA12 { get; set; }
        public float CurrentMAEPMA24 { get; set; }
        public float CurrentMAEPMA168 { get; set; }
        public float CurrentMAHMA6 { get; set; }
        public float CurrentMAHMA12 { get; set; }
        public float CurrentMAHMA24 { get; set; }
        public float CurrentMAHMA168 { get; set; }
        public float CurrentMAKAMAER { get; set; }
        public float CurrentMAKAMAKama { get; set; }
        public float CurrentMAMAMAMAMA { get; set; }
        public float CurrentMAMAMAFAMA { get; set; }
        public float CurrentMASMA12Sma { get; set; }
        public float CurrentMASMA12Mad { get; set; }
        public float CurrentMASMA12Mse { get; set; }
        public float CurrentMASMA12Mape { get; set; }
        public float CurrentMASMA24Sma { get; set; }
        public float CurrentMASMA24Mad { get; set; }
        public float CurrentMASMA24Mse { get; set; }
        public float CurrentMASMA24Mape { get; set; }
        public float CurrentMASMA168Sma { get; set; }
        public float CurrentMASMA168Mad { get; set; }
        public float CurrentMASMA168Mse { get; set; }
        public float CurrentMASMA168Mape { get; set; }
        public float CurrentMASMMA6 { get; set; }
        public float CurrentMASMMA12 { get; set; }
        public float CurrentMASMMA24 { get; set; }
        public float CurrentMASMMA168 { get; set; }
        public float CurrentMAT3_6 { get; set; }
        public float CurrentMAT3_12 { get; set; }
        public float CurrentMAT3_24 { get; set; }
        public float CurrentMAT3_168 { get; set; }
        public float CurrentMATEMA6 { get; set; }
        public float CurrentMATEMA12 { get; set; }
        public float CurrentMATEMA24 { get; set; }
        public float CurrentMATEMA168 { get; set; }
        public float CurrentMAWMA6 { get; set; }
        public float CurrentMAWMA12 { get; set; }
        public float CurrentMAWMA24 { get; set; }
        public float CurrentMAWMA168 { get; set; }
        public float CurrentMAVWMA6 { get; set; }
        public float CurrentMAVWMA12 { get; set; }
        public float CurrentMAVWMA24 { get; set; }
        public float CurrentMAVWMA168 { get; set; }
        public float CurrentMomentumAbsolutePriceOscillator { get; set; }
        public float CurrentMomentumAwesomeOscillatorOscillator { get; set; }
        public float CurrentMomentumAwesomeOscillatorNormalized { get; set; }
        public float CurrentMomentumBalanceOfPower { get; set; }
        public float CurrentMomentumChandeMomentumOscillator { get; set; }
        public float CurrentMomentumCommodityChannelIndex { get; set; }
        public float CurrentMomentumCommoditySelectionIndexCsi { get; set; }
        public float CurrentMomentumCommoditySelectionIndexSignal { get; set; }
        public float CurrentMomentumConnorsRSIRsi { get; set; }
        public float CurrentMomentumConnorsRSIRsiStreak { get; set; }
        public float CurrentMomentumConnorsRSIPercentRank { get; set; }
        public float CurrentMomentumConnorsRSIConnorsRsi { get; set; }
        public float CurrentMomentumDetrendedPriceOscillatorSma { get; set; }
        public float CurrentMomentumDetrendedPriceOscillatorDpo { get; set; }
        public float CurrentMomentumElderRayIndexBull { get; set; }
        public float CurrentMomentumElderRayIndexBear { get; set; }
        public float CurrentMomentumGatorOscillatorUpper { get; set; }
        public float CurrentMomentumGatorOscillatorLower { get; set; }
        public bool CurrentMomentumGatorOscillatorUpperExpanding { get; set; }
        public bool CurrentMomentumGatorOscillatorLowerExpanding { get; set; }
        public float CurrentMomentumMACDMacd { get; set; }
        public float CurrentMomentumMACDSignal { get; set; }
        public float CurrentMomentumMACDHistogram { get; set; }
        public float CurrentMomentumOnBalanceVolumeObv { get; set; }
        public float CurrentMomentumOnBalanceVolumeSma { get; set; }
        public float CurrentMomentumPercentagePriceOscillatorPpo { get; set; }
        public float CurrentMomentumPercentagePriceOscillatorSignal { get; set; }
        public float CurrentMomentumPercentagePriceOscillatorHistogram { get; set; }
        public float CurrentMomentumPriceMomentumOscillatorPmo { get; set; }
        public float CurrentMomentumPriceMomentumOscillatorSignal { get; set; }
        public float CurrentMomentumRateOfChangeMomentum { get; set; }
        public float CurrentMomentumRateOfChangeRoc { get; set; }
        public float CurrentMomentumRateOfChangeSma { get; set; }
        public float CurrentMomentumRelativeStrengthIndex { get; set; }
        public float CurrentMomentumRocWithBandsRoc { get; set; }
        public float CurrentMomentumRocWithBandsEma { get; set; }
        public float CurrentMomentumRocWithBandsUpper { get; set; }
        public float CurrentMomentumRocWithBandsLower { get; set; }
        public float CurrentMomentumSchaffTrendCycle { get; set; }
        public float CurrentMomentumStochasticFastOscillatorSfo { get; set; }
        public float CurrentMomentumStochasticFastOscillatorSignal { get; set; }
        public float CurrentMomentumStochasticMomentumIndexSmi { get; set; }
        public float CurrentMomentumStochasticMomentumIndexSignal { get; set; }
        public float CurrentMomentumStochasticOscillatorOscillator { get; set; }
        public float CurrentMomentumStochasticOscillatorSignal { get; set; }
        public float CurrentMomentumStochasticOscillatorPercentJ { get; set; }
        public float CurrentMomentumStochasticRSIStochRsi { get; set; }
        public float CurrentMomentumStochasticRSISignal { get; set; }
        public float CurrentMomentumTRIXEMA3 { get; set; }
        public float CurrentMomentumTRIXTrix { get; set; }
        public float CurrentMomentumTRIXSignal { get; set; }
        public float CurrentMomentumTrueStrengthIndexTsi { get; set; }
        public float CurrentMomentumTrueStrengthIndexSignal { get; set; }
        public float CurrentMomentumUltimateOscillator { get; set; }
        public float CurrentMomentumWilliamsR { get; set; }
        public float CurrentOtherIndicatorsFractalChaosBandsUpper { get; set; }
        public float CurrentOtherIndicatorsFractalChaosBandsLower { get; set; }
        public float CurrentOtherIndicatorsHurstExponent { get; set; }
        public float CurrentOtherIndicatorsPivotHighPoint { get; set; }
        public float CurrentOtherIndicatorsPivotLowPoint { get; set; }
        public float CurrentOtherIndicatorsPivotHighLine { get; set; }
        public float CurrentOtherIndicatorsPivotLowLine { get; set; }
        public float CurrentOtherIndicatorsPivotPointsR1 { get; set; }
        public float CurrentOtherIndicatorsPivotPointsR2 { get; set; }
        public float CurrentOtherIndicatorsPivotPointsR3 { get; set; }
        public float CurrentOtherIndicatorsPivotPointsPP { get; set; }
        public float CurrentOtherIndicatorsPivotPointsS1 { get; set; }
        public float CurrentOtherIndicatorsPivotPointsS2 { get; set; }
        public float CurrentOtherIndicatorsPivotPointsS3 { get; set; }
        public float CurrentOtherIndicatorsPriceRelativeStrengthPrs { get; set; }
        public float CurrentOtherIndicatorsPriceRelativeStrengthSma { get; set; }
        public float CurrentOtherIndicatorsPriceRelativeStrengthPercent { get; set; }
        public float CurrentOtherIndicatorsProjectionOscillatorPbo { get; set; }
        public float CurrentOtherIndicatorsProjectionOscillatorSignal { get; set; }
        public float CurrentOtherIndicatorsRollingPivotPointsR1 { get; set; }
        public float CurrentOtherIndicatorsRollingPivotPointsR2 { get; set; }
        public float CurrentOtherIndicatorsRollingPivotPointsR3 { get; set; }
        public float CurrentOtherIndicatorsRollingPivotPointsPP { get; set; }
        public float CurrentOtherIndicatorsRollingPivotPointsS1 { get; set; }
        public float CurrentOtherIndicatorsRollingPivotPointsS2 { get; set; }
        public float CurrentOtherIndicatorsRollingPivotPointsS3 { get; set; }
        public float CurrentOtherIndicatorsWilliamsFractalFractalBear { get; set; }
        public float CurrentOtherIndicatorsWilliamsFractalFractalBull { get; set; }
        public float CurrentOtherIndicatorsVerticalHorizontalFilterVhf { get; set; }
        public float CurrentOtherIndicatorsVerticalHorizontalFilterSignal { get; set; }
        public bool CurrentPeakHighestHigh { get; set; }
        public float CurrentPeakOffsetPreviousHH { get; set; }
        public float CurrentPeakOffsetNextHH { get; set; }
        public bool CurrentPeakLowestLow { get; set; }
        public float CurrentPeakOffsetPreviousLL { get; set; }
        public float CurrentPeakOffsetNextLL { get; set; }
        public float CurrentReturnDayReturn { get; set; }
        public float CurrentReturnDayInterval { get; set; }
        public float CurrentReturnDayRank2 { get; set; }
        public float CurrentReturnDayRank3 { get; set; }
        public float CurrentReturnDayRank4 { get; set; }
        public float CurrentReturnDayRank6 { get; set; }
        public float CurrentReturnDayRank8 { get; set; }
        public float CurrentReturnDayRank12 { get; set; }
        public float CurrentReturnTwoDayReturn { get; set; }
        public float CurrentReturnTwoDayInterval { get; set; }
        public float CurrentReturnTwoDayRank2 { get; set; }
        public float CurrentReturnTwoDayRank3 { get; set; }
        public float CurrentReturnTwoDayRank4 { get; set; }
        public float CurrentReturnTwoDayRank6 { get; set; }
        public float CurrentReturnTwoDayRank8 { get; set; }
        public float CurrentReturnTwoDayRank12 { get; set; }
        public float CurrentReturnWeekReturn { get; set; }
        public float CurrentReturnWeekInterval { get; set; }
        public float CurrentReturnWeekRank2 { get; set; }
        public float CurrentReturnWeekRank3 { get; set; }
        public float CurrentReturnWeekRank4 { get; set; }
        public float CurrentReturnWeekRank6 { get; set; }
        public float CurrentReturnWeekRank8 { get; set; }
        public float CurrentReturnWeekRank12 { get; set; }
        public float CurrentTrendSlopeHigh6 { get; set; }
        public float CurrentTrendSlopeHigh8 { get; set; }
        public float CurrentTrendSlopeHigh12 { get; set; }
        public float CurrentTrendSlopeHigh24 { get; set; }
        public float CurrentTrendSlopeLow6 { get; set; }
        public float CurrentTrendSlopeLow8 { get; set; }
        public float CurrentTrendSlopeLow12 { get; set; }
        public float CurrentTrendSlopeLow24 { get; set; }
        public float CurrentTrendAroonUp { get; set; }
        public float CurrentTrendAroonDown { get; set; }
        public float CurrentTrendAroonOscillator { get; set; }
        public float CurrentTrendADXPdi { get; set; }
        public float CurrentTrendADXMdi { get; set; }
        public float CurrentTrendADXAdx { get; set; }
        public float CurrentTrendADXAdxr { get; set; }
        public float CurrentTrendAtrTrailingStopAtrStop { get; set; }
        public float CurrentTrendAtrTrailingStopBuyStop { get; set; }
        public float CurrentTrendAtrTrailingStopSellStop { get; set; }
        public float CurrentTrendChandelierExitShort { get; set; }
        public float CurrentTrendChandelierExitLong { get; set; }
        public float CurrentTrendHilbertTransformDominantCyclePeriods { get; set; }
        public float CurrentTrendHilbertTransformTrendLine { get; set; }
        public float CurrentTrendHilbertTransformSmoothPrice { get; set; }
        public float CurrentTrendIchimokuCloudSignal { get; set; }
        public float CurrentTrendIchimokuCloudBase { get; set; }
        public float CurrentTrendIchimokuCloudLeadingA { get; set; }
        public float CurrentTrendIchimokuCloudLeadingB { get; set; }
        public float CurrentTrendIchimokuCloudLagging { get; set; }
        public float CurrentTrendMcGinleyDynamicMcGinleyDynamic6 { get; set; }
        public float CurrentTrendMcGinleyDynamicMcGinleyDynamic12 { get; set; }
        public float CurrentTrendMcGinleyDynamicMcGinleyDynamic24 { get; set; }
        public float CurrentTrendMcGinleyDynamicMcGinleyDynamic168 { get; set; }
        public float CurrentTrendMovingAverageEnvelopeUpper { get; set; }
        public float CurrentTrendMovingAverageEnvelopeCenter { get; set; }
        public float CurrentTrendMovingAverageEnvelopeLower { get; set; }
        public float CurrentTrendParabolicSARSAR { get; set; }
        public bool CurrentTrendParabolicSARIsReversal { get; set; }
        public float CurrentTrendSuperTrendCombined { get; set; }
        public float CurrentTrendSuperTrendUpper { get; set; }
        public float CurrentTrendSuperTrendLower { get; set; }
        public float CurrentTrendVortexIndicatorPvi { get; set; }
        public float CurrentTrendVortexIndicatorNvi { get; set; }
        public float CurrentTrendWilliamsAlligatorJaw { get; set; }
        public float CurrentTrendWilliamsAlligatorTeeth { get; set; }
        public float CurrentTrendWilliamsAlligatorLips { get; set; }
        public float CurrentVolatilityATR12TR { get; set; }
        public float CurrentVolatilityATR12Atr { get; set; }
        public float CurrentVolatilityATR12Atrp { get; set; }
        public float CurrentVolatilityATR24TR { get; set; }
        public float CurrentVolatilityATR24Atr { get; set; }
        public float CurrentVolatilityATR24Atrp { get; set; }
        public float CurrentVolatilityATR168TR { get; set; }
        public float CurrentVolatilityATR168Atr { get; set; }
        public float CurrentVolatilityATR168Atrp { get; set; }
        public float CurrentVolatilityBollingerBandsUpper { get; set; }
        public float CurrentVolatilityBollingerBandsLower { get; set; }
        public float CurrentVolatilityBollingerBandsPercentB { get; set; }
        public float CurrentVolatilityBollingerBandsZScore { get; set; }
        public float CurrentVolatilityBollingerBandsWidth { get; set; }
        public float CurrentVolatilityChoppinessIndex { get; set; }
        public float CurrentVolatilityDonchianChannelsUpper { get; set; }
        public float CurrentVolatilityDonchianChannelsCenter { get; set; }
        public float CurrentVolatilityDonchianChannelsLower { get; set; }
        public float CurrentVolatilityDonchianChannelsWidth { get; set; }
        public float CurrentVolatilityHistoricalVolatility { get; set; }
        public float CurrentVolatilityKeltnerChannelsUpper { get; set; }
        public float CurrentVolatilityKeltnerChannelsCenter { get; set; }
        public float CurrentVolatilityKeltnerChannelsLower { get; set; }
        public float CurrentVolatilityKeltnerChannelsWidth { get; set; }
        public float CurrentVolatilityStandardDeviationChannelUpper { get; set; }
        public float CurrentVolatilityStandardDeviationChannelCenter { get; set; }
        public float CurrentVolatilityStandardDeviationChannelLower { get; set; }
        public bool CurrentVolatilityStandardDeviationChannelBreakPoint { get; set; }
        public float CurrentVolatilityStarcBandUpper { get; set; }
        public float CurrentVolatilityStarcBandCenter { get; set; }
        public float CurrentVolatilityStarcBandLower { get; set; }
        public float CurrentVolatilityUlcerIndex { get; set; }
        public float CurrentVolatilityVolatilityStopSAR { get; set; }
        public bool CurrentVolatilityVolatilityStopIsStop { get; set; }
        public float CurrentVolatilityVolatilityStopUpper { get; set; }
        public float CurrentVolatilityVolatilityStopLower { get; set; }
        public float CurrentVolumesAccumulationDistributionLineMoneyFlowMultiplier { get; set; }
        public float CurrentVolumesAccumulationDistributionLineMoneyFlowVolume { get; set; }
        public float CurrentVolumesAccumulationDistributionLineAdl { get; set; }
        public float CurrentVolumesAccumulationDistributionLineAdlSma { get; set; }
        public float CurrentVolumesChaikinMoneyFlowMoneyFlowMultiplier { get; set; }
        public float CurrentVolumesChaikinMoneyFlowMoneyFlowVolume { get; set; }
        public float CurrentVolumesChaikinMoneyFlowCmf { get; set; }
        public float CurrentVolumesChaikinOscillatorMoneyFlowMultiplier { get; set; }
        public float CurrentVolumesChaikinOscillatorMoneyFlowVolume { get; set; }
        public float CurrentVolumesChaikinOscillatorAdl { get; set; }
        public float CurrentVolumesChaikinOscillatorOscillator { get; set; }
        public float CurrentVolumesForceIndex { get; set; }
        public float CurrentVolumesKlingerVolumeOscillatorOscillator { get; set; }
        public float CurrentVolumesKlingerVolumeOscillatorSignal { get; set; }
        public float CurrentVolumesMoneyFlowIndex { get; set; }
        public float CurrentVolumesPercentageVolumeOscillatorPvo { get; set; }
        public float CurrentVolumesPercentageVolumeOscillatorSignal { get; set; }
        public float CurrentVolumesPercentageVolumeOscillatorHistogram { get; set; }

        public float NextOpen { get; set; }
        public float NextHigh { get; set; }
        public float NextLow { get; set; }
        public float NextClose { get; set; }
        public float NextVolume { get; set; }
        public float NextQuoteVolume { get; set; }
        public float NextBuyVolume { get; set; }
        public float NextBuyQuoteVolume { get; set; }
        public float NextMarketCap { get; set; }
        public float NextAvgOHLC { get; set; }
        public float NextAvgHLC { get; set; }
        public float NextAvgHL { get; set; }
        public float NextAvgOC { get; set; }
        public float NextProportionUpper { get; set; }
        public float NextProportionBody { get; set; }
        public float NextProportionLower { get; set; }
        public float NextLengthCandle { get; set; }
        public float NextLengthUpper { get; set; }
        public float NextLengthBody { get; set; }
        public float NextLengthLower { get; set; }
        public bool NextCandleSticksAbandonedBabyBearish { get; set; }
        public bool NextCandleSticksAbandonedBabyBullish { get; set; }
        public bool NextCandleSticksAboveTheStomach { get; set; }
        public bool NextCandleSticksAdvanceBlock { get; set; }
        public bool NextCandleSticksBelowTheStomach { get; set; }
        public bool NextCandleSticksBeltHoldBearish { get; set; }
        public bool NextCandleSticksBeltHoldBullish { get; set; }
        public bool NextCandleSticksBreakawayBearish { get; set; }
        public bool NextCandleSticksBreakawayBullish { get; set; }
        public bool NextCandleSticksCandleBlack { get; set; }
        public bool NextCandleSticksCandleShortBlack { get; set; }
        public bool NextCandleSticksCandleShortWhite { get; set; }
        public bool NextCandleSticksCandleWhite { get; set; }
        public bool NextCandleSticksConcealingBabySwallow { get; set; }
        public bool NextCandleSticksCounterAttackBearish { get; set; }
        public bool NextCandleSticksCounterAttackBullish { get; set; }
        public bool NextCandleSticksDarkCloudCover { get; set; }
        public bool NextCandleSticksDeliberation { get; set; }
        public bool NextCandleSticksDoji { get; set; }
        public bool NextCandleSticksDojiDragonfly { get; set; }
        public bool NextCandleSticksDojiGappingDown { get; set; }
        public bool NextCandleSticksDojiGappingUp { get; set; }
        public bool NextCandleSticksDojiGravestone { get; set; }
        public bool NextCandleSticksDojiLongLegged { get; set; }
        public bool NextCandleSticksDojiNorthern { get; set; }
        public bool NextCandleSticksDojiSouthern { get; set; }
        public bool NextCandleSticksDojiStarBearish { get; set; }
        public bool NextCandleSticksDojiStarBullish { get; set; }
        public bool NextCandleSticksDojiStarCollapsing { get; set; }
        public bool NextCandleSticksDownsideGapThreeMethods { get; set; }
        public bool NextCandleSticksDownsideTasukiGap { get; set; }
        public bool NextCandleSticksEngulfingBearish { get; set; }
        public bool NextCandleSticksEngulfingBullish { get; set; }
        public bool NextCandleSticksEveningDojiStar { get; set; }
        public bool NextCandleSticksEveningStar { get; set; }
        public bool NextCandleSticksFallingThreeMethods { get; set; }
        public bool NextCandleSticksHammer { get; set; }
        public bool NextCandleSticksHammerInverted { get; set; }
        public bool NextCandleSticksHangingMan { get; set; }
        public bool NextCandleSticksHaramiBearish { get; set; }
        public bool NextCandleSticksHaramiBullish { get; set; }
        public bool NextCandleSticksHaramiCrossBearish { get; set; }
        public bool NextCandleSticksHaramiCrossBullish { get; set; }
        public bool NextCandleSticksHighWaveBearish { get; set; }
        public bool NextCandleSticksHighWaveBullish { get; set; }
        public bool NextCandleSticksHikkakeBearish { get; set; }
        public bool NextCandleSticksHikkakeBullish { get; set; }
        public bool NextCandleSticksHikkakeModBearish { get; set; }
        public bool NextCandleSticksHikkakeModBullish { get; set; }
        public bool NextCandleSticksHomingPidgeon { get; set; }
        public bool NextCandleSticksIdenticalThreeCrows { get; set; }
        public bool NextCandleSticksInNeck { get; set; }
        public bool NextCandleSticksKickingBearish { get; set; }
        public bool NextCandleSticksKickingBullish { get; set; }
        public bool NextCandleSticksKickingByLengthBearish { get; set; }
        public bool NextCandleSticksKickingByLengthBullish { get; set; }
        public bool NextCandleSticksLadderBottom { get; set; }
        public bool NextCandleSticksLastEngulfingBottom { get; set; }
        public bool NextCandleSticksLastEngulfingTop { get; set; }
        public bool NextCandleSticksLongBlackDay { get; set; }
        public bool NextCandleSticksLongWhiteDay { get; set; }
        public bool NextCandleSticksMarubozuBlack { get; set; }
        public bool NextCandleSticksMarubozuClosingBlack { get; set; }
        public bool NextCandleSticksMarubozuClosingWhite { get; set; }
        public bool NextCandleSticksMarubozuOpeningBlack { get; set; }
        public bool NextCandleSticksMarubozuOpeningWhite { get; set; }
        public bool NextCandleSticksMarubozuWhite { get; set; }
        public bool NextCandleSticksMatchingLow { get; set; }
        public bool NextCandleSticksMatHold { get; set; }
        public bool NextCandleSticksMeetingLinesBearish { get; set; }
        public bool NextCandleSticksMeetingLinesBullish { get; set; }
        public bool NextCandleSticksMorningDojiStar { get; set; }
        public bool NextCandleSticksMorningStar { get; set; }
        public bool NextCandleSticksOnNeck { get; set; }
        public bool NextCandleSticksPiercingPattern { get; set; }
        public bool NextCandleSticksRickshawMan { get; set; }
        public bool NextCandleSticksRisingThreeMethods { get; set; }
        public bool NextCandleSticksSeparatingLinesBearish { get; set; }
        public bool NextCandleSticksSeparatingLinesBullish { get; set; }
        public bool NextCandleSticksShootingStarOneCandle { get; set; }
        public bool NextCandleSticksShootingStarTwoCandle { get; set; }
        public bool NextCandleSticksShortLineBearish { get; set; }
        public bool NextCandleSticksShortLineBullish { get; set; }
        public bool NextCandleSticksSideBySideWhiteLinesBearish { get; set; }
        public bool NextCandleSticksSideBySideWhiteLinesBullish { get; set; }
        public bool NextCandleSticksSpinningTopBlack { get; set; }
        public bool NextCandleSticksSpinningTopWhite { get; set; }
        public bool NextCandleSticksStalledPattern { get; set; }
        public bool NextCandleSticksStickSandwich { get; set; }
        public bool NextCandleSticksTakuriLine { get; set; }
        public bool NextCandleSticksThreeBlackCrows { get; set; }
        public bool NextCandleSticksThreeInsideDown { get; set; }
        public bool NextCandleSticksThreeInsideUp { get; set; }
        public bool NextCandleSticksThreeLineStrikeBearish { get; set; }
        public bool NextCandleSticksThreeLineStrikeBullish { get; set; }
        public bool NextCandleSticksThreeOutsideDown { get; set; }
        public bool NextCandleSticksThreeOutsideUp { get; set; }
        public bool NextCandleSticksThreeStarsInTheSouth { get; set; }
        public bool NextCandleSticksThreeWhiteSoldiers { get; set; }
        public bool NextCandleSticksThrusting { get; set; }
        public bool NextCandleSticksTriStarBearish { get; set; }
        public bool NextCandleSticksTriStarBullish { get; set; }
        public bool NextCandleSticksTweezersBottom { get; set; }
        public bool NextCandleSticksTweezersTop { get; set; }
        public bool NextCandleSticksTwoBlackGappingCandles { get; set; }
        public bool NextCandleSticksTwoCrows { get; set; }
        public bool NextCandleSticksUniqueThreeRiverBottom { get; set; }
        public bool NextCandleSticksUpsideGapSideBySideWhiteLineBearish { get; set; }
        public bool NextCandleSticksUpsideGapSideBySideWhiteLineBullish { get; set; }
        public bool NextCandleSticksUpsideGapThreeMethods { get; set; }
        public bool NextCandleSticksUpsideGapTwoCrows { get; set; }
        public bool NextCandleSticksUpsideTasukiGap { get; set; }
        public bool NextCandleSticksWindowFalling { get; set; }
        public bool NextCandleSticksWindowRising { get; set; }
        public float NextCyclesEhlersAdaptiveCyberCycleCycle { get; set; }
        public float NextCyclesEhlersAdaptiveCyberCyclePeriod { get; set; }
        public float NextCyclesEhlersCombFilterSpectralEstimate { get; set; }
        public float NextCyclesEhlersCyberCycle { get; set; }
        public float NextCyclesEhlersCycleAmplitude { get; set; }
        public float NextCyclesEhlersCycleBandPassFilter { get; set; }
        public float NextCyclesEhlersDualDifferentiatorDominantCycle { get; set; }
        public float NextCyclesEhlersEvenBetterSineWaveIndicator { get; set; }
        public float NextCyclesEhlersFourierSeriesAnalysisWave { get; set; }
        public float NextCyclesEhlersFourierSeriesAnalysisRoc { get; set; }
        public float NextCyclesEhlersHomodyneDominantCycle { get; set; }
        public float NextCyclesEhlersInstantaneousPhaseIndicator { get; set; }
        public float NextCyclesEhlersPhaseAccumulationDominantCycle { get; set; }
        public float NextCyclesEhlersSimpleCycleIndicator { get; set; }
        public float NextCyclesEhlersSineWaveIndicatorV1Sine { get; set; }
        public float NextCyclesEhlersSineWaveIndicatorV1LeadSine { get; set; }
        public float NextCyclesEhlersSineWaveIndicatorV2Sine { get; set; }
        public float NextCyclesEhlersSineWaveIndicatorV2LeadSine { get; set; }
        public float NextCyclesEhlersSpectrumDerivedFilterBank { get; set; }
        public float NextCyclesEhlersSquelchIndicator { get; set; }
        public float NextCyclesEhlersStochasticCyberCycleCycle { get; set; }
        public float NextCyclesEhlersStochasticCyberCycleSignal { get; set; }
        public float NextCyclesEhlersZeroCrossingsDominantCycle { get; set; }
        public float NextCyclesGroverLlorensCycleOscillator { get; set; }
        public float NextCyclesHurstCycleChannelFastUpperBand { get; set; }
        public float NextCyclesHurstCycleChannelSlowUpperBand { get; set; }
        public float NextCyclesHurstCycleChannelFastMiddleBand { get; set; }
        public float NextCyclesHurstCycleChannelSlowMiddleBand { get; set; }
        public float NextCyclesHurstCycleChannelFastLowerBand { get; set; }
        public float NextCyclesHurstCycleChannelSlowLowerBand { get; set; }
        public float NextCyclesHurstCycleChannelOMed { get; set; }
        public float NextCyclesHurstCycleChannelOShort { get; set; }
        public float NextCyclesSimpleCycle { get; set; }
        public float NextMAALMA6 { get; set; }
        public float NextMAALMA12 { get; set; }
        public float NextMAALMA24 { get; set; }
        public float NextMAALMA168 { get; set; }
        public float NextMADEMA6 { get; set; }
        public float NextMADEMA12 { get; set; }
        public float NextMADEMA24 { get; set; }
        public float NextMADEMA168 { get; set; }
        public float NextMAEMA6 { get; set; }
        public float NextMAEMA12 { get; set; }
        public float NextMAEMA24 { get; set; }
        public float NextMAEMA168 { get; set; }
        public float NextMAEPMA6 { get; set; }
        public float NextMAEPMA12 { get; set; }
        public float NextMAEPMA24 { get; set; }
        public float NextMAEPMA168 { get; set; }
        public float NextMAHMA6 { get; set; }
        public float NextMAHMA12 { get; set; }
        public float NextMAHMA24 { get; set; }
        public float NextMAHMA168 { get; set; }
        public float NextMAKAMAER { get; set; }
        public float NextMAKAMAKama { get; set; }
        public float NextMAMAMAMAMA { get; set; }
        public float NextMAMAMAFAMA { get; set; }
        public float NextMASMA12Sma { get; set; }
        public float NextMASMA12Mad { get; set; }
        public float NextMASMA12Mse { get; set; }
        public float NextMASMA12Mape { get; set; }
        public float NextMASMA24Sma { get; set; }
        public float NextMASMA24Mad { get; set; }
        public float NextMASMA24Mse { get; set; }
        public float NextMASMA24Mape { get; set; }
        public float NextMASMA168Sma { get; set; }
        public float NextMASMA168Mad { get; set; }
        public float NextMASMA168Mse { get; set; }
        public float NextMASMA168Mape { get; set; }
        public float NextMASMMA6 { get; set; }
        public float NextMASMMA12 { get; set; }
        public float NextMASMMA24 { get; set; }
        public float NextMASMMA168 { get; set; }
        public float NextMAT3_6 { get; set; }
        public float NextMAT3_12 { get; set; }
        public float NextMAT3_24 { get; set; }
        public float NextMAT3_168 { get; set; }
        public float NextMATEMA6 { get; set; }
        public float NextMATEMA12 { get; set; }
        public float NextMATEMA24 { get; set; }
        public float NextMATEMA168 { get; set; }
        public float NextMAWMA6 { get; set; }
        public float NextMAWMA12 { get; set; }
        public float NextMAWMA24 { get; set; }
        public float NextMAWMA168 { get; set; }
        public float NextMAVWMA6 { get; set; }
        public float NextMAVWMA12 { get; set; }
        public float NextMAVWMA24 { get; set; }
        public float NextMAVWMA168 { get; set; }
        public float NextMomentumAbsolutePriceOscillator { get; set; }
        public float NextMomentumAwesomeOscillatorOscillator { get; set; }
        public float NextMomentumAwesomeOscillatorNormalized { get; set; }
        public float NextMomentumBalanceOfPower { get; set; }
        public float NextMomentumChandeMomentumOscillator { get; set; }
        public float NextMomentumCommodityChannelIndex { get; set; }
        public float NextMomentumCommoditySelectionIndexCsi { get; set; }
        public float NextMomentumCommoditySelectionIndexSignal { get; set; }
        public float NextMomentumConnorsRSIRsi { get; set; }
        public float NextMomentumConnorsRSIRsiStreak { get; set; }
        public float NextMomentumConnorsRSIPercentRank { get; set; }
        public float NextMomentumConnorsRSIConnorsRsi { get; set; }
        public float NextMomentumDetrendedPriceOscillatorSma { get; set; }
        public float NextMomentumDetrendedPriceOscillatorDpo { get; set; }
        public float NextMomentumElderRayIndexBull { get; set; }
        public float NextMomentumElderRayIndexBear { get; set; }
        public float NextMomentumGatorOscillatorUpper { get; set; }
        public float NextMomentumGatorOscillatorLower { get; set; }
        public bool NextMomentumGatorOscillatorUpperExpanding { get; set; }
        public bool NextMomentumGatorOscillatorLowerExpanding { get; set; }
        public float NextMomentumMACDMacd { get; set; }
        public float NextMomentumMACDSignal { get; set; }
        public float NextMomentumMACDHistogram { get; set; }
        public float NextMomentumOnBalanceVolumeObv { get; set; }
        public float NextMomentumOnBalanceVolumeSma { get; set; }
        public float NextMomentumPercentagePriceOscillatorPpo { get; set; }
        public float NextMomentumPercentagePriceOscillatorSignal { get; set; }
        public float NextMomentumPercentagePriceOscillatorHistogram { get; set; }
        public float NextMomentumPriceMomentumOscillatorPmo { get; set; }
        public float NextMomentumPriceMomentumOscillatorSignal { get; set; }
        public float NextMomentumRateOfChangeMomentum { get; set; }
        public float NextMomentumRateOfChangeRoc { get; set; }
        public float NextMomentumRateOfChangeSma { get; set; }
        public float NextMomentumRelativeStrengthIndex { get; set; }
        public float NextMomentumRocWithBandsRoc { get; set; }
        public float NextMomentumRocWithBandsEma { get; set; }
        public float NextMomentumRocWithBandsUpper { get; set; }
        public float NextMomentumRocWithBandsLower { get; set; }
        public float NextMomentumSchaffTrendCycle { get; set; }
        public float NextMomentumStochasticFastOscillatorSfo { get; set; }
        public float NextMomentumStochasticFastOscillatorSignal { get; set; }
        public float NextMomentumStochasticMomentumIndexSmi { get; set; }
        public float NextMomentumStochasticMomentumIndexSignal { get; set; }
        public float NextMomentumStochasticOscillatorOscillator { get; set; }
        public float NextMomentumStochasticOscillatorSignal { get; set; }
        public float NextMomentumStochasticOscillatorPercentJ { get; set; }
        public float NextMomentumStochasticRSIStochRsi { get; set; }
        public float NextMomentumStochasticRSISignal { get; set; }
        public float NextMomentumTRIXEMA3 { get; set; }
        public float NextMomentumTRIXTrix { get; set; }
        public float NextMomentumTRIXSignal { get; set; }
        public float NextMomentumTrueStrengthIndexTsi { get; set; }
        public float NextMomentumTrueStrengthIndexSignal { get; set; }
        public float NextMomentumUltimateOscillator { get; set; }
        public float NextMomentumWilliamsR { get; set; }
        public float NextOtherIndicatorsFractalChaosBandsUpper { get; set; }
        public float NextOtherIndicatorsFractalChaosBandsLower { get; set; }
        public float NextOtherIndicatorsHurstExponent { get; set; }
        public float NextOtherIndicatorsPivotHighPoint { get; set; }
        public float NextOtherIndicatorsPivotLowPoint { get; set; }
        public float NextOtherIndicatorsPivotHighLine { get; set; }
        public float NextOtherIndicatorsPivotLowLine { get; set; }
        public float NextOtherIndicatorsPivotPointsR1 { get; set; }
        public float NextOtherIndicatorsPivotPointsR2 { get; set; }
        public float NextOtherIndicatorsPivotPointsR3 { get; set; }
        public float NextOtherIndicatorsPivotPointsPP { get; set; }
        public float NextOtherIndicatorsPivotPointsS1 { get; set; }
        public float NextOtherIndicatorsPivotPointsS2 { get; set; }
        public float NextOtherIndicatorsPivotPointsS3 { get; set; }
        public float NextOtherIndicatorsPriceRelativeStrengthPrs { get; set; }
        public float NextOtherIndicatorsPriceRelativeStrengthSma { get; set; }
        public float NextOtherIndicatorsPriceRelativeStrengthPercent { get; set; }
        public float NextOtherIndicatorsProjectionOscillatorPbo { get; set; }
        public float NextOtherIndicatorsProjectionOscillatorSignal { get; set; }
        public float NextOtherIndicatorsRollingPivotPointsR1 { get; set; }
        public float NextOtherIndicatorsRollingPivotPointsR2 { get; set; }
        public float NextOtherIndicatorsRollingPivotPointsR3 { get; set; }
        public float NextOtherIndicatorsRollingPivotPointsPP { get; set; }
        public float NextOtherIndicatorsRollingPivotPointsS1 { get; set; }
        public float NextOtherIndicatorsRollingPivotPointsS2 { get; set; }
        public float NextOtherIndicatorsRollingPivotPointsS3 { get; set; }
        public float NextOtherIndicatorsWilliamsFractalFractalBear { get; set; }
        public float NextOtherIndicatorsWilliamsFractalFractalBull { get; set; }
        public float NextOtherIndicatorsVerticalHorizontalFilterVhf { get; set; }
        public float NextOtherIndicatorsVerticalHorizontalFilterSignal { get; set; }
        public bool NextPeakHighestHigh { get; set; }
        public float NextPeakOffsetPreviousHH { get; set; }
        public float NextPeakOffsetNextHH { get; set; }
        public bool NextPeakLowestLow { get; set; }
        public float NextPeakOffsetPreviousLL { get; set; }
        public float NextPeakOffsetNextLL { get; set; }
        public float NextReturnDayReturn { get; set; }
        public float NextReturnDayInterval { get; set; }
        public float NextReturnDayRank2 { get; set; }
        public float NextReturnDayRank3 { get; set; }
        public float NextReturnDayRank4 { get; set; }
        public float NextReturnDayRank6 { get; set; }
        public float NextReturnDayRank8 { get; set; }
        public float NextReturnDayRank12 { get; set; }
        public float NextReturnTwoDayReturn { get; set; }
        public float NextReturnTwoDayInterval { get; set; }
        public float NextReturnTwoDayRank2 { get; set; }
        public float NextReturnTwoDayRank3 { get; set; }
        public float NextReturnTwoDayRank4 { get; set; }
        public float NextReturnTwoDayRank6 { get; set; }
        public float NextReturnTwoDayRank8 { get; set; }
        public float NextReturnTwoDayRank12 { get; set; }
        public float NextReturnWeekReturn { get; set; }
        public float NextReturnWeekInterval { get; set; }
        public float NextReturnWeekRank2 { get; set; }
        public float NextReturnWeekRank3 { get; set; }
        public float NextReturnWeekRank4 { get; set; }
        public float NextReturnWeekRank6 { get; set; }
        public float NextReturnWeekRank8 { get; set; }
        public float NextReturnWeekRank12 { get; set; }
        public float NextTrendSlopeHigh6 { get; set; }
        public float NextTrendSlopeHigh8 { get; set; }
        public float NextTrendSlopeHigh12 { get; set; }
        public float NextTrendSlopeHigh24 { get; set; }
        public float NextTrendSlopeLow6 { get; set; }
        public float NextTrendSlopeLow8 { get; set; }
        public float NextTrendSlopeLow12 { get; set; }
        public float NextTrendSlopeLow24 { get; set; }
        public float NextTrendAroonUp { get; set; }
        public float NextTrendAroonDown { get; set; }
        public float NextTrendAroonOscillator { get; set; }
        public float NextTrendADXPdi { get; set; }
        public float NextTrendADXMdi { get; set; }
        public float NextTrendADXAdx { get; set; }
        public float NextTrendADXAdxr { get; set; }
        public float NextTrendAtrTrailingStopAtrStop { get; set; }
        public float NextTrendAtrTrailingStopBuyStop { get; set; }
        public float NextTrendAtrTrailingStopSellStop { get; set; }
        public float NextTrendChandelierExitShort { get; set; }
        public float NextTrendChandelierExitLong { get; set; }
        public float NextTrendHilbertTransformDominantCyclePeriods { get; set; }
        public float NextTrendHilbertTransformTrendLine { get; set; }
        public float NextTrendHilbertTransformSmoothPrice { get; set; }
        public float NextTrendIchimokuCloudSignal { get; set; }
        public float NextTrendIchimokuCloudBase { get; set; }
        public float NextTrendIchimokuCloudLeadingA { get; set; }
        public float NextTrendIchimokuCloudLeadingB { get; set; }
        public float NextTrendIchimokuCloudLagging { get; set; }
        public float NextTrendMcGinleyDynamicMcGinleyDynamic6 { get; set; }
        public float NextTrendMcGinleyDynamicMcGinleyDynamic12 { get; set; }
        public float NextTrendMcGinleyDynamicMcGinleyDynamic24 { get; set; }
        public float NextTrendMcGinleyDynamicMcGinleyDynamic168 { get; set; }
        public float NextTrendMovingAverageEnvelopeUpper { get; set; }
        public float NextTrendMovingAverageEnvelopeCenter { get; set; }
        public float NextTrendMovingAverageEnvelopeLower { get; set; }
        public float NextTrendParabolicSARSAR { get; set; }
        public bool NextTrendParabolicSARIsReversal { get; set; }
        public float NextTrendSuperTrendCombined { get; set; }
        public float NextTrendSuperTrendUpper { get; set; }
        public float NextTrendSuperTrendLower { get; set; }
        public float NextTrendVortexIndicatorPvi { get; set; }
        public float NextTrendVortexIndicatorNvi { get; set; }
        public float NextTrendWilliamsAlligatorJaw { get; set; }
        public float NextTrendWilliamsAlligatorTeeth { get; set; }
        public float NextTrendWilliamsAlligatorLips { get; set; }
        public float NextVolatilityATR12TR { get; set; }
        public float NextVolatilityATR12Atr { get; set; }
        public float NextVolatilityATR12Atrp { get; set; }
        public float NextVolatilityATR24TR { get; set; }
        public float NextVolatilityATR24Atr { get; set; }
        public float NextVolatilityATR24Atrp { get; set; }
        public float NextVolatilityATR168TR { get; set; }
        public float NextVolatilityATR168Atr { get; set; }
        public float NextVolatilityATR168Atrp { get; set; }
        public float NextVolatilityBollingerBandsUpper { get; set; }
        public float NextVolatilityBollingerBandsLower { get; set; }
        public float NextVolatilityBollingerBandsPercentB { get; set; }
        public float NextVolatilityBollingerBandsZScore { get; set; }
        public float NextVolatilityBollingerBandsWidth { get; set; }
        public float NextVolatilityChoppinessIndex { get; set; }
        public float NextVolatilityDonchianChannelsUpper { get; set; }
        public float NextVolatilityDonchianChannelsCenter { get; set; }
        public float NextVolatilityDonchianChannelsLower { get; set; }
        public float NextVolatilityDonchianChannelsWidth { get; set; }
        public float NextVolatilityHistoricalVolatility { get; set; }
        public float NextVolatilityKeltnerChannelsUpper { get; set; }
        public float NextVolatilityKeltnerChannelsCenter { get; set; }
        public float NextVolatilityKeltnerChannelsLower { get; set; }
        public float NextVolatilityKeltnerChannelsWidth { get; set; }
        public float NextVolatilityStandardDeviationChannelUpper { get; set; }
        public float NextVolatilityStandardDeviationChannelCenter { get; set; }
        public float NextVolatilityStandardDeviationChannelLower { get; set; }
        public bool NextVolatilityStandardDeviationChannelBreakPoint { get; set; }
        public float NextVolatilityStarcBandUpper { get; set; }
        public float NextVolatilityStarcBandCenter { get; set; }
        public float NextVolatilityStarcBandLower { get; set; }
        public float NextVolatilityUlcerIndex { get; set; }
        public float NextVolatilityVolatilityStopSAR { get; set; }
        public bool NextVolatilityVolatilityStopIsStop { get; set; }
        public float NextVolatilityVolatilityStopUpper { get; set; }
        public float NextVolatilityVolatilityStopLower { get; set; }
        public float NextVolumesAccumulationDistributionLineMoneyFlowMultiplier { get; set; }
        public float NextVolumesAccumulationDistributionLineMoneyFlowVolume { get; set; }
        public float NextVolumesAccumulationDistributionLineAdl { get; set; }
        public float NextVolumesAccumulationDistributionLineAdlSma { get; set; }
        public float NextVolumesChaikinMoneyFlowMoneyFlowMultiplier { get; set; }
        public float NextVolumesChaikinMoneyFlowMoneyFlowVolume { get; set; }
        public float NextVolumesChaikinMoneyFlowCmf { get; set; }
        public float NextVolumesChaikinOscillatorMoneyFlowMultiplier { get; set; }
        public float NextVolumesChaikinOscillatorMoneyFlowVolume { get; set; }
        public float NextVolumesChaikinOscillatorAdl { get; set; }
        public float NextVolumesChaikinOscillatorOscillator { get; set; }
        public float NextVolumesForceIndex { get; set; }
        public float NextVolumesKlingerVolumeOscillatorOscillator { get; set; }
        public float NextVolumesKlingerVolumeOscillatorSignal { get; set; }
        public float NextVolumesMoneyFlowIndex { get; set; }
        public float NextVolumesPercentageVolumeOscillatorPvo { get; set; }
        public float NextVolumesPercentageVolumeOscillatorSignal { get; set; }
        public float NextVolumesPercentageVolumeOscillatorHistogram { get; set; }


    }